### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by penleychan** [sojinsamuel/stackoverflow-clone#4]
This is an exact copy one to one to a recent NestJS course from jsmastery. https://www.jsmastery.pro/ultimate-next13-course

Give credit where it is due, while I don't know what their stances are on you putting their work on public, you should consult with them before doing so.

**Comment by sojinsamuel** [comment]
Thanks for reaching out @penleychan 
Just reached out to adrian, i think this answers your query. Sorry if i made you misunderstand :pray: 
![Screenshot from 2023-10-16 12-13-45](https://github.com/sojinsamuel/stackoverflow-clone/assets/77185816/db52a0be-d620-4c8b-9ba8-f4b76db66721)

**Comment by sojinsamuel** [comment]
Thanks for reaching out @penleychan

I was also in a hurry to clarify the doubt. Sorry if i made you misunderstand :pray: 
![Screenshot from 2023-10-16 12-13-45](https://github.com/sojinsamuel/stackoverflow-clone/assets/77185816/b438ef67-f6ea-41c8-af2f-f74e194ac845)

**Comment by penleychan** [comment]
If that's the case, I apologize for the misunderstanding.
